### ISSUE TITLE
ホーム画面のデザイン

### ISSUE THREAD

**Issue by kdix-23-071** [NID-kt/toryumon-team-f#34]
## 機能の説明
ホーム画面のデザインを考える
## 実装内容 または やること
Figmaを使ってホーム画面のデザインを考える
 

- [x] 担当者を決める　
- [ ] 必要であれば 細かい issue に分割する。

## 進め方 方針

- [ ] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [ ] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

-

**Comment by TBSten** [comment]
📝 
次回定例(8/8)までにラフでもいいので作成してもらう

**Comment by TBSten** [comment]
Next Action
- [くまちゃんの配置の仕方を決める](https://www.figma.com/design/ccbn5tzDDsSkV0OQLPMPmO/%E3%81%A6%E3%81%8F%E3%81%A6%E3%81%8F%E3%83%80%E3%82%A4%E3%82%A8%E3%83%83%E3%83%88?node-id=61-20&t=AS5BGysOzMX6O4QJ-4)

**Comment by TBSten** [comment]
Next Action

- 8/29までにホーム画面の3Dモデルをつくりきる

**Comment by TBSten** [comment]
完了 by @kdix-23-071 
https://www.figma.com/design/ccbn5tzDDsSkV0OQLPMPmO/%E3%81%A6%E3%81%8F%E3%81%A6%E3%81%8F%E3%83%80%E3%82%A4%E3%82%A8%E3%83%83%E3%83%88?node-id=1-37&t=7CjFQF3niAomxdjj-4
